#!/bin/bash -e

#	mstdnlambda
#	Copyright (C) 2022 Battams, Derek <derek@battams.ca>
#
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; either version 2 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License along
#	with this program; if not, write to the Free Software Foundation, Inc.,
#	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

show_help() {
cat << EOF
  Usage: ${0##*/} [-acho]
  Build this project, producing all binaries in build/bin
  -a Do a build for AWS Lambda
       Binaries are built for linux/amd64 and Lambda zip files are created in
       build/zip for each binary
  -c Clean the build directory (destroy it completely) before build starts 
  -o Clean only then exit
  -h Dispaly this help and exit; ignore all other options 
EOF
}

qpopd() {
  popd &> /dev/null
}

ZIP="zip"

while getopts acho opt; do
  case $opt in
    a)
      DOLAMBDA=1
      ;;
    c)
      DOCLEAN=1
      ;;
    o)
      CLEANONLY=1
      ;;
    *)
      show_help >&2
      exit 1
  esac
done

pushd `dirname $0` &> /dev/null
trap qpopd EXIT

if [[ -n $DOCLEAN || -n $CLEANONLY ]]; then
  go clean
  rm -rf build
  if [[ -n $CLEANONLY ]]; then
    exit 0
  fi
fi

BIN="build/bin"
ZIP="build/zip"
TGTS=`find ./cmd -maxdepth 1 -mindepth 1 -type d -print`

mkdir -p $BIN
if [[ -n $DOLAMBDA ]]; then
  mkdir -p $ZIP
fi

for t in $TGTS; do
  name=`basename $t`
  os=`uname -s`
  if [[ -z $DOLAMBDA && ($os == MINGW* || $os == CYGWIN*) ]]; then
    ZIP="build-lambda-zip -output"
    name=$name.exe
  fi
  echo "Building ${name}..."
  if [[ -n $DOLAMBDA ]]; then
    export GOOS=linux
    export GOARCH=amd64
  fi
  go build -o build/bin/$name $t
  if [[ -n $DOLAMBDA ]]; then
    $ZIP $ZIP/$name.zip $BIN/$name 
  fi
done
